server: github
repo: "octocat/Hello-World"
pr_id: 1

github:
  token: "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"

gitlab:
  url: "https://gitlab.com"
  token: "glpat-_lD7SYWxmzxX8kKYcd_TuW86MQp1OmkzY3N5Cw.01.1216r1cw0"

bitbucket:
  username: "Ayushi Mishra"
  password: "@Ayushi20"

