server: github
repo: "octocat/Hello-World"
pr_id: 1

github:
  token: "${GITHUB_TOKEN}"

gitlab:
  url: "https://gitlab.com"
  token: "${GITLAB_TOKEN}"

bitbucket:
  username: "${BITBUCKET_USER}"
  password: "${BITBUCKET_PASS}"
